name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04] 
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies (${{ matrix.os }}) # OS-specific dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            # Install dependencies for ubuntu-latest
            sudo apt-get update
            sudo apt-get install -y linux-headers-generic
          elif [[ "${{ matrix.os }}" == "ubuntu-20.04" ]]; then
            # Install dependencies for ubuntu-20.04
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          elif [[ "${{ matrix.os }}" == "ubuntu-18.04" ]]; then
            # Install dependencies for ubuntu-18.04
            sudo apt-get update
            sudo apt-get install -y linux-headers-$(uname -r)
          fi
      - name: Make (${{ matrix.os }})
        run: make

